def menu():
    print("------------------------------------------------")
    print("|             ~  MENU PRINCIPAL  ~             |")
    print("------------------------------------------------")
    print("   ")
    print("1️⃣  Détecter version d'une adresse IP")
    print("2️⃣  Lister les fichiers d’un dossier")
    print("3️⃣  Copier un fichier avec date (fonction)")
    print("4️⃣  Utiliser la classe GestionnaireFichiers")
    print("5️⃣  Exporter les infos système (Exo 6 - Q1)")
    print("6️⃣  Exporter tous les processus (Exo 6 - Q2)")
    print("7️⃣  Afficher processus > 2% RAM (Exo 6 - Q3)")
    print("8️⃣  Analyser un fichier avec Pandas (Exo 7)")
    print("9️⃣  Lister interfaces réseau locales (Exo 8 - Q1)")
    print("🔟 Lister interfaces réseau d’une VM distante (Exo 8 - Q2)")
    print("   ")
    print("0️⃣  Quitter")
    print("   ")
